### ISSUE TITLE
How to connect tectile sensors in icub simulator through  python code 

### ISSUE THREAD

**Issue by ArfnZl** [robotology/robotology-superbuild#985] opened 2022-01-03 15:38 UTC
Please  provide any example  to connect tectile sensor in icub silmulator hands through  python

**Comment by ArfnZl** [comment] 2022-01-09 17:57
The problem is not with port just give you an example of Python code skin sensor reading

**Comment by traversaro** [comment] 2022-01-10 16:04
Hi @ArfnZl, as this issue seems to be a duplicate of https://github.com/robotology/robotology-superbuild/issues/963, I will close it. Sorry for this, but please avoid to open duplicate issue for the same problem.

**Closed by traversaro** 2022-01-10 16:04 UTC
